package presenter;

import models.GeneralTree;
import models.Node;
import views.MainFrame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class Presenter implements ActionListener {

    private MainFrame mainFrame;

    public Presenter(){
        this.mainFrame = new MainFrame(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        switch (e.getActionCommand()){
            case "Enter Grammar":
                this.enterGrammar();
            case "Añadir":
                this.saveGrammar();
                break;
            case "View General Tree":
                this.viewGeneralTree();
                break;
            case "Cancelar":
                this.cancelAddGrammar();
        }
    }


    private void enterGrammar(){
        this.mainFrame.showEnterGrammar();
    }

    public void saveGrammar(){
        this.mainFrame.getTerminalSymbols();
        this.mainFrame.hideCreateDialog();
    }


    public void cancelAddGrammar(){
        this.mainFrame.hideCreateDialog();
    }

    private void viewGeneralTree() {
        ArrayList<String> nonTerminalSymbolsList = new ArrayList<>();
        nonTerminalSymbolsList.add("S");
        nonTerminalSymbolsList.add("S");
        nonTerminalSymbolsList.add("S");
        ArrayList<String> terminalSymbolsList = new ArrayList<>();
        terminalSymbolsList.add("a");
        terminalSymbolsList.add("Sa");
        terminalSymbolsList.add("Sb");

        GeneralTree generalTree = new GeneralTree(terminalSymbolsList,nonTerminalSymbolsList, new Node("S"));
        generalTree.addNewNode();
        //generalTree.showNodeList();
        this.mainFrame.showGeneralDerivationTreePaintedPanel(generalTree.rootNode);

    }

    private void validateGrammar(){
        //Call arrays generated by front
        //Verify not empty
        //Verify sets disjunction
        //Verify axiomatic isn't empty
    }

    public static void main(String[] args) {
        new Presenter();

        /**

        ArrayList<String> nonTerminalSymbolsList = new ArrayList<>();
        nonTerminalSymbolsList.add("S");
        nonTerminalSymbolsList.add("S");
        nonTerminalSymbolsList.add("S");
        ArrayList<String> terminalSymbolsList = new ArrayList<>();
        terminalSymbolsList.add("a");
        terminalSymbolsList.add("Sa");
        terminalSymbolsList.add("Sb");

        GeneralTree generalTree = new GeneralTree(terminalSymbolsList,nonTerminalSymbolsList, new Node("S"));
        generalTree.addNewNode();
        generalTree.showNodeList();

         */

    }
}
